#!/bin/sh
# record rectangle with slop + byzanz
# usage: byz [duration]

eval $(slop)
if [ -z $1 ]; then
	byzanz-record -x ${X} -y ${Y} -w ${W} -h ${H} -v -d 15 $(date +%s).gif
else
	byzanz-record -x ${X} -y ${Y} -w ${W} -h ${H} -v -d $1 $(date +%s).gif
fi
