#!/bin/sh
# get current memory

t=$(grep MemTotal /proc/meminfo | awk '{print $2}')
f=$(grep MemFree  /proc/meminfo | awk '{print $2}')
b=$(grep ^Buffers /proc/meminfo | awk '{print $2}')
c=$(grep ^Cached  /proc/meminfo | awk '{print $2}')

echo "100 * ($t - $f - $c - $b) / $t" | bc
