#!/bin/sh
# dmenu with custom options

width=256
height=16
font="Clear Sans:size=11"
lines=5

# screen width, width offset, height offset
sw=$(wattr w $(lsw -r))
sh=$(wattr h $(lsw -r))
xo=$(((sw - width)/2))
#yo=$(((sh - height)/2))
yo=0

dmenu -fn "${font}" -l ${lines} \
      -nb '#09090d' -nf '#839496' \
      -sb '#09090d' -sf '#58698c' \
      -w ${width} -h ${height} \
      -x ${xo} -y ${yo} $@
