#!/bin/sh
# dmenu with custom options

. $XDG_CONFIG_HOME/wm.conf

WIDTH=256
HEIGHT=16
FONT="Metis"

# screen width, width offset, height offset
SW=$(wattr w $(lsw -r))
SH=$(wattr h $(lsw -r))
XO=$(((SW - WIDTH)/2))
YO=$(((SH - HEIGHT)/2))

dmenu -fn ${FONT} -l 0 \
      -nb '#09090d' -nf '#839496' \
      -sb '#09090d' -sf '#58698c' \
      -w ${WIDTH} -h ${HEIGHT} \
      -x ${XO} -y ${YO} $@
