#!/bin/sh
# wrapper for notifications
# usage: <command> | notify

. $WMCONF

DURATION=${DURATION:-"3"}
FONT=${FONT:-"metis"}

SW=$(wattr w $(lsw -r))
W=256
H=48
XO=$((SW - W - GAP))
YO=$((PANELHEIGHT + GAP))

(echo "%{c}$(cat /dev/stdin)"; sleep $DURATION) | bar -d -g "${W}x${H}+${XO}+${YO}" -f $FONT -B "#ff09090d" -F "#ff839496"
