#!/bin/sh
# notification daemon

. $XDG_CONFIG_HOME/wm.conf

# appearance
width=256
height=48
font='Clear Sans:size=11'
fgc='#839496'
bgc='#09090d'
duration=3

# screen width, width offset, height offset
sw=$(wattr w $(lsw -r))
xo=$((sw - width - GAP))
yo=$((PANELHEIGHT + GAP))

# named pipe
fifo=$TMPDIR/notify
[ -p $fifo ] || mkfifo $fifo

# main loop
tail -f $fifo | while read line; do {
	echo "$line"
	sleep $duration
} | skroll -r \
  | lemonbar -g ${width}x${height}+${xo}+${yo} \
             -d -f$font -F$fgc -B$bgc
done
