#!/bin/sh
# wrapper for notifications
# usage: <command> | notify

. $WMCONF

WIDTH=256
HEIGHT=48
BG=${BG:-"#ff09090d"}
FG=${FG:-"#ff839496"}
FONT=${FONT:-"metis"}
DURATION=${DURATION:-"3"}

# screen width, width offset, height offset
SW=$(wattr w $(lsw -r))
XO=$((SW - WIDTH - GAP))
YO=$((PANELHEIGHT + GAP))

{
	printf '%%{c}'
	cat
	sleep $DURATION
} | bar -df $FONT -B $BG -F $FG \
	-g ${WIDTH}x${HEIGHT}+${XO}+${YO}
