#!/bin/sh
# notification daemon

. $XDG_CONFIG_HOME/wm.conf

# appearance
width=256
height=48
font='Clear Sans:size=12'
fgc='#ff839496'
bgc='#ff09090d'
duration="0.10"

# screen width, width offset, height offset
sw=$(wattr w $(lsw -r))
xo=$((sw - width - GAP))
yo=$((PANELHEIGHT + GAP))

# main loop
notifyterm | while read line; do {
	echo "$line"
} | skroll -r -n 10 -d $duration \
  | while read sline; do 
	  echo "%{c}$sline"
    done | lemonbar -g ${width}x${height}+${xo}+${yo} \
	                -d -f"$font" -F$fgc -B$bgc
done
