#!/bin/sh
# panel script

. $XDG_CONFIG_HOME/wm.conf

# set colors
ffg='%{F#ff839496}'
bfg='%{B#ff839496}'
fhl='%{F#ff58698c}'
bhl='%{B#ff58698c}'
blw='%{F#ff353540}'
fbg='%{F#ff09090d}'
bbg='%{B#ff09090d}'

# workspace indicators
wi() {
	wsm status | sed -e s/0/${blw}0/g -e s/1/${fhl}1/g
}

# invoke panel
while :; do
	# set bg/fg
	bar="$ffg$bbg"

	# left section
	bar="$bar %{l}"
	# music
	bar="$bar ${fhl}MUSIC"
	bar="$bar ${ffg}$(mpc current)${fbg}"

	# center section
	bar="$bar %{c}"
	# window groups
	bar="$bar $(wi)"

	# right section
	bar="$bar %{r}"
	# cpu
	bar="$bar ${fhl}CPU${ffg}"
	bar="$bar $(cpu)"
	# memory
	bar="$bar ${fhl}MEM${ffg}"
	bar="$bar $(memory)"
	# volume
	#bar="$bar ${fhl}VOL${ffg}"
	#bar="$bar $(volume)"
	# clock
	bar="$bar ${fhl}TIME${bbg}"
	bar="$bar ${ffg}$(date '+%T')"

	echo "$bar "
	sleep 0.35;
done | lemonbar -g $(wattr w $(lsw -r))x${PANELHEIGHT}x0x0 \
                -df 'Nimbus Sans L:size=12' -f 'M+ 1m'
