#!/bin/sh
# panel script

. $WMCONF

# set colors
bfg='%{F#ff839496}'
bhl='%{F#ff58698c}'
blw='%{F#ff353540}'
bbg='%{B#ff09090d}'

pb() {
	progressbar | sed -e 0,//s//${blw}/ -e 0,//s//${bhl}/
}

# group indicators
gi() {
	wmstatus | sed -e s/0/${blw}/g -e s/1/${bhl}/g
}

# invoke panel
while :; do
	# set bg/fg
    bar="$bfg$bbg"

	# left section
	bar="$bar %{l}"
	# icon and button to kill current window
	bar="$bar $bhl%{A:killwa $(pfw):}✗%{A}"
	# window title
	bar="$bar $bfg$(pfw)"

	# center section
	bar="$bar %{c}"
	# window groups
	bar="$bar $(gi)"

	# right section
	bar="$bar %{r}"
	# cpu
	bar="$bar ${bhl}"
	bar="$bar $(cpu | pb)"
	# memory
	bar="$bar ${bhl}"
	bar="$bar $(memory | pb)"
	# volume
	bar="$bar ${bhl}"
	bar="$bar $(volume | pb)"
	# clock
	bar="$bar ${bhl}${bfg}"
	bar="$bar $(date '+%T')"
	echo "$bar "
	sleep 0.2;
done | bar -df Metis -g x$PANELHEIGHT | while read line; do eval $line; done
