#!/bin/sh
# screenshot window with a gap around the window

. $XDG_CONFIG_HOME/wm.conf

eval $(slop -b1 -l -c 0.3,0.3,0.5,0.3)

X=$((X - GAP))
Y=$((Y - GAP))
W=$((W + 2*GAP))
H=$((H + 2*GAP))

maim -g ${W}x${H}+${X}+${Y}
